### ISSUE TITLE
Is this lesson text correct?

### ISSUE THREAD

**Issue by jessenovotny** [learn-co-curriculum/ruby-orm#11]
In the example code, we're provide with #self.save to push information into the database as so...

`def self.save(name, breed, age, database_connection)
    database_connection.execute("INSERT INTO cats (name, breed, age) VALUES (?, ?, ?)",name, breed, age)
  end`

Shouldn't `name`, `breed`, and `age` be interpolated into the `execute("...")` string using `#{name}`, #{breed}`, and`#{age}`?

Like so...

`def self.save(name, breed, age, database_connection)
    database_connection.execute("INSERT INTO cats (name, breed, age) VALUES (#{name}, #{breed}, #{age}")
  end`

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
