### ISSUE TITLE
class method `save` should be `create`

### ISSUE THREAD

**Issue by alexgriff** [learn-co-curriculum/ruby-orm#12]
I raised an issue in the pokemon-scraper lab that follows this in the curriculum because it uses the same pattern presented here in this readme. 

This reading defines a class method `.save` that instantiates a new instance as well as persists to the db.  Following the previous patterns presented in the OO Ruby section and, more importantly, following the conventions that will be used once we get to ActiveRecord a method with this behavior should be called `.create`.  I've encountered this causing some confusion with students.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by DanielSeehausen** [comment]
In following up with Alex's issue comment above: 
current state of readme: any instantiation of ruby instances is happening outside of ```.save``` method, which is now only persisting a record in the database
