### ISSUE TITLE
Lab suggests schema_migration.sql is populated

### ISSUE THREAD

**Issue by rohanphillips** [learn-co-curriculum/ruby-orm#15]
The lab suggests schema_migration.sql is populated, it is not.

If it's not, please update the lab so that the user knows they need to create the table.

**Comment by sgharms** [comment]
@rohanphillips Looking at the README I don't see the word `schema_migration.sql`. Can you provide me a link to what you're viewing? Or is this issue opened on the wrong repo? Let us know. Thanks!

**Comment by rohanphillips** [comment]
Hmm, sorry about that, pokemon-scraper-online-web-sp-000 is where I thought I'd posted the question

**Comment by sgharms** [comment]
Ah gotcha. Could you duplicate this over there? I don't have the ability to move issues between repos. We're looking to do a heavy revisit of that lab this quarter so your request is very timely.
