### ISSUE TITLE
Duplicate Lesson

### ISSUE THREAD

**Issue by NStephenson** [learn-co-curriculum/ruby-orm#9]
This lesson and "How Ruby Talks to SQL" are the exact same. I'm not sure if this is intentional.

**Comment by AnnJohn** [comment]
thanks for raising this @NStephenson. We'll be updating the first instance of this to better explain how Ruby talks to SQL without diving too much into ORMs.

**Comment by AnnJohn** [comment]
thanks again @NStephenson. We're going to keep this lesson here as is and remove the previous, initial one.
